services:
  sws-auto-bot:
    build: .
    container_name: sws-auto-bot
    restart: "no"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/__pycache__
    ipc: host
    ulimits:
      core:
        soft: 0
        hard: 0
    environment:
      - HEADLESS=true
